FROM gcr.io/cloud-marketplace-tools/k8s/deployer_envsubst:latest

# Copy marketplace schema and manifest into expected locations
COPY k8s/marketplace/schema.yaml /schema.yaml
COPY k8s/marketplace/manifest /manifest
