apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
  - hpa.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: pmomax-pid-architect
