apiVersion: batch/v1
kind: Job
metadata:
  name: ${APP_INSTANCE_NAME}-tester
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_INSTANCE_NAME}
    component: tester
  annotations:
    marketplace.cloud.google.com/verification: "test"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: ${APP_INSTANCE_NAME}
        component: tester
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: ${TESTER_IMAGE}
          args:
            - /bin/sh
            - -c
            - "curl -fsS http://${APP_INSTANCE_NAME}:80/health"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
