steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'us-docker.pkg.dev/katalyststreet-public/pmomax/deployer:1.0.7'
      - '-f'
      - 'deployer/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      - 'push'
      - 'us-docker.pkg.dev/katalyststreet-public/pmomax/deployer:1.0.7'
    waitFor: ['build']

images:
  - 'us-docker.pkg.dev/katalyststreet-public/pmomax/deployer:1.0.7'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
