APP_INSTANCE_NAME: pmo-architect
NAMESPACE: pmomax
DOMAIN: pmomax.example.com
reportingSecret: reporting-secret
deployerServiceAccount: deployer-sa

# Image properties
# Deployer image used by Marketplace installer
deployerImageRepo: us-docker.pkg.dev/katalyststreet-public/pmomax/deployer
deployerImageTag: "1.0"

# PMOMax app image
pmomaxAppRepo: us-east1-docker.pkg.dev/katalyststreet-public/apps/pmo-architect
pmomaxAppTag: "1.0.1"
PMOMAX_APP_PORT: "8080"
TESTER_IMAGE: curlimages/curl:8.12.1
PARTNER_ID: katalyststreet
PRODUCT_ID: pmomax
GCP_PROJECT_ID: katalyststreet-public
