APP_INSTANCE_NAME: pmo-architect
NAMESPACE: pmomax
DOMAIN: pmomax.example.com
reportingSecret: reporting-secret
deployerServiceAccount: deployer-sa

# Image properties
# Deployer image used by Marketplace installer
deployerImageRepo: us-docker.pkg.dev/katalyststreet-public/pmomax/deployer
deployerImageTag: 1.0.1

# PMOMax app image
pmomaxAppRepo: us-docker.pkg.dev/katalyststreet-public/pmomax/pmomax
pmomaxAppTag: 1.0.0
PMOMAX_APP_PORT: "8080"
