apiVersion: v1
kind: ConfigMap
metadata:
  name: pmomax-config
  labels:
    app.kubernetes.io/name: pmomax
data:
  NODE_ENV: "production"
  PORT: "8080"
  LLM_PROVIDER: "google"
  IBM_WX_REGION: "us-south"
