apiVersion: v1
kind: Secret
metadata:
  name: pmomax-secrets
  labels:
    app.kubernetes.io/name: pmomax
type: Opaque
stringData:
  GOOGLE_API_KEY: ""
  IBM_WX_APIKEY: ""
  IBM_WX_PROJECT_ID: ""
  IBM_WX_MODEL_ID: ""
